import type React from 'react';
import { ArticleWidget } from '@/components/widgets/article/ArticleWidget';
import { BioWidget } from '@/components/widgets/bio/BioWidget';
import { ClockWidget } from '@/components/widgets/clock/ClockWidget';
import { CommitWidget } from '@/components/widgets/commit/CommitWidget';
import { ContactWidget } from '@/components/widgets/contact/ContactWidget';
import { CvWidget } from '@/components/widgets/cv/CvWidget';
import { LinkedInWidget } from '@/components/widgets/linkedin/LinkedInWidget';
import { LocationWidget } from '@/components/widgets/location/LocationWidget';
import { PortfolioWidget } from '@/components/widgets/portfolio/PortfolioWidget';
import { SwitcherWidget } from '@/components/widgets/switcher/SwitcherWidget';
import { WorkWidget } from '@/components/widgets/work/WorkWidget';

type GridItem = {
	i: string;
	component: React.ComponentType;
};

export const gridItems: GridItem[] = [
	{ i: 'bio', component: BioWidget },
	{ i: 'location', component: LocationWidget },
	{ i: 'cv', component: CvWidget },
	{ i: 'commit', component: CommitWidget },
	{ i: 'article', component: ArticleWidget },
	{ i: 'switcher', component: SwitcherWidget },
	{ i: 'linkedin', component: LinkedInWidget },
	{ i: 'contact', component: ContactWidget },
	{ i: 'portfolio', component: PortfolioWidget },
	{ i: 'work', component: WorkWidget },
	{ i: 'clock', component: ClockWidget },
];

export const layouts: any = {
	all: {
		lg: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'location', x: 2, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'article', x: 0, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'linkedin', x: 1, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 1, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 3, w: 2, h: 1, isResizable: false },
		],
		md: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 2, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 3, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 2, w: 2, h: 2, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'article', x: 0, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 2, y: 3, w: 2, h: 2, isResizable: false },
		],
		sm: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 0, y: 2, w: 2, h: 1.5, isResizable: false },
			{ i: 'cv', x: 1, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 1, y: 5, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 6, w: 2, h: 1.25, isResizable: false },
			{ i: 'switcher', x: 0, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 3, w: 2, h: 1.25, isResizable: false },
			{ i: 'article', x: 0, y: 8, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 0, y: 9, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 10, w: 2, h: 2, isResizable: false },
		],
	},
	about: {
		lg: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'location', x: 2, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 2, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'commit', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'article', x: 0, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'linkedin', x: 3, y: 4, w: 1, h: 1, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'contact', x: 0, y: 1, w: 2, h: 1, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 3, w: 2, h: 1, isResizable: false },
		],
		md: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 2, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 3, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 2, w: 2, h: 2, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'article', x: 0, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 2, y: 3, w: 2, h: 2, isResizable: false },
		],
		sm: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 0, y: 2, w: 2, h: 1.5, isResizable: false },
			{ i: 'cv', x: 1, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 1, y: 5, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 6, w: 2, h: 1.25, isResizable: false },
			{ i: 'switcher', x: 0, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 3, w: 2, h: 1.25, isResizable: false },
			{ i: 'article', x: 0, y: 8, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 0, y: 9, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 10, w: 2, h: 2, isResizable: false },
		],
	},
	projects: {
		lg: [
			{ i: 'bio', x: 0, y: 3, w: 2, h: 1, isResizable: false },
			{ i: 'location', x: 3, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'cv', x: 2, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 1, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'article', x: 0, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'linkedin', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 1, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 0, w: 2, h: 1, isResizable: false },
		],
		md: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 2, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 3, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 2, w: 2, h: 2, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'article', x: 0, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 2, y: 3, w: 2, h: 2, isResizable: false },
		],
		sm: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 0, y: 2, w: 2, h: 1.5, isResizable: false },
			{ i: 'cv', x: 1, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 1, y: 5, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 6, w: 2, h: 1.25, isResizable: false },
			{ i: 'switcher', x: 0, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 3, w: 2, h: 1.25, isResizable: false },
			{ i: 'article', x: 0, y: 8, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 0, y: 9, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 10, w: 2, h: 2, isResizable: false },
		],
	},
	blog: {
		lg: [
			{ i: 'bio', x: 0, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'location', x: 0, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 1, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'article', x: 0, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'linkedin', x: 1, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 1, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 2, y: 0, w: 2, h: 1, isResizable: false },
		],
		md: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 2, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 3, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 2, w: 2, h: 2, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'article', x: 0, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 2, y: 3, w: 2, h: 2, isResizable: false },
		],
		sm: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 0, y: 2, w: 2, h: 1.5, isResizable: false },
			{ i: 'cv', x: 1, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 1, y: 5, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 6, w: 2, h: 1.25, isResizable: false },
			{ i: 'switcher', x: 0, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 3, w: 2, h: 1.25, isResizable: false },
			{ i: 'article', x: 0, y: 8, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 0, y: 9, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 10, w: 2, h: 2, isResizable: false },
		],
	},
	misc: {
		lg: [
			{ i: 'bio', x: 3, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'location', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 0, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 1, w: 1, h: 1, isResizable: false },
			{ i: 'article', x: 0, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'linkedin', x: 1, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'switcher', x: 1, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 1, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 3, w: 2, h: 1, isResizable: false },
		],
		md: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 2, y: 0, w: 2, h: 1, isResizable: false },
			{ i: 'cv', x: 3, y: 0, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 3, y: 2, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 2, w: 2, h: 2, isResizable: false },
			{ i: 'switcher', x: 3, y: 2, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'article', x: 0, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 2, y: 3, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 2, y: 1, w: 1, h: 2, isResizable: false },
			{ i: 'work', x: 2, y: 3, w: 2, h: 2, isResizable: false },
		],
		sm: [
			{ i: 'bio', x: 0, y: 0, w: 2, h: 2, isResizable: false },
			{ i: 'location', x: 0, y: 2, w: 2, h: 1.5, isResizable: false },
			{ i: 'cv', x: 1, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'clock', x: 1, y: 5, w: 2, h: 1, isResizable: false },
			{ i: 'commit', x: 0, y: 6, w: 2, h: 1.25, isResizable: false },
			{ i: 'switcher', x: 0, y: 3, w: 1, h: 1, isResizable: false },
			{ i: 'linkedin', x: 0, y: 3, w: 2, h: 1.25, isResizable: false },
			{ i: 'article', x: 0, y: 8, w: 2, h: 2, isResizable: false },
			{ i: 'contact', x: 0, y: 9, w: 2, h: 2, isResizable: false },
			{ i: 'portfolio', x: 0, y: 4, w: 2, h: 2, isResizable: false },
			{ i: 'work', x: 0, y: 10, w: 2, h: 2, isResizable: false },
		],
	},
};
